spring:
  profiles:
    active: dev
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
server:
  session:
    timeout: 86400000
# mybatis
mybatis_config_file: mybatis-config.xml
mapper_path: /mapper/**.xml
entity_package: com.xl.backen.entity

# 权限菜单配置
permission:
  menusModel: task,activity,community,permiss,trash,people,volunteer,shop,app,garbage