server:
    port: 8090
    servlet:
      context-path: /backen
jdbc:
  driver: com.mysql.jdbc.Driver
  url: jdbc:mysql://localhost:3306/db_backen?userUnicode=true&characterEncoding=utf-8&useSSL=false
  username: root
  password: Xlmysql2018.

filePath: /work/projects/front/static/
nginxPath:  http://120.79.177.219:8060/static/